### ISSUE TITLE
Error when I ran the code "deepen.plot_domains(adata)"

### ISSUE THREAD

**Issue by yunbokai** [JiangBioLab/DeepST#1]
Dear Author;
       When I ran the code "deepen.plot_domains(adata)" with the data provided in "DeepST/data",
       I got something wrong:
`>>> deepen.plot_domains(adata)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yunsy\DeepST\deepst\DeepST.py", line 375, in plot_domains
    if isinstance(self.data_name, str):
AttributeError: 'run' object has no attribute 'data_name'`

    However, when  I ran the code "deepen.plot_umap(adata)", I successfully got the umap plot like this
![图片](https://user-images.githubusercontent.com/94819980/197403613-c1fa2524-e12b-4232-bdb6-c55948bc3e21.png)
    Can you help me?
    
Here is my code:

```
import os
from DeepST import run
import matplotlib.pyplot as plt
from pathlib import Path

data_path = "../data" #### to your path
data_name = '151673' #### project name
save_path = "../Results" #### save path
n_domains = 7 ###### the number of spatial domains.
deepen = run(save_path = save_path,
        platform = "Visium",
        pca_n_comps = 200,
        pre_epochs = 800,
        Conv_type="GCNConv", #### you can choose GNN types.
        )
adata = deepen._get_adata(data_path, data_name)
adata = deepen._get_augment(adata, adjacent_weight = 0.3, neighbour_k = 4,)
graph_dict = deepen._get_graph(adata.obsm["spatial"], distType="BallTree", k=12)
adata = deepen._fit(adata, graph_dict, pretrain = False)
adata = deepen._get_cluster_data(adata, n_domains = n_domains, priori=True) ###### without using prior knowledge, setting priori = False.
######## spatial domains
**deepen.plot_domains(adata)**  ERROR!!!
######## UMAP
deepen.plot_umap(adata)   
...
```

Best wishes,
18K

**Comment by yunbokai** [comment]
![图片](https://user-images.githubusercontent.com/94819980/198997524-4b181f39-c18e-4de1-8597-27467aee6bbf.png)

**Comment by yunbokai** [comment]
![图片](https://user-images.githubusercontent.com/94819980/198997608-b468e019-3823-4fb0-8973-1fed5985af84.png)
same problem，But I can get the graph here.

**Comment by JiangBioLab** [comment]
Thanks, we have improved this section. You can re-run this part of your code, and welcome to contact us again (xuchang0214@163.com) if you have any question.

**Comment by yunbokai** [comment]
I replaced the DeepST.py and re-ran my code .But there is a new Error.
![图片](https://user-images.githubusercontent.com/94819980/199223777-39ad69d2-87f8-4583-b827-d700e119aba5.png)

**Comment by 1warm** [comment]
same problem,is your question solved?

**Comment by yunbokai** [comment]
> same problem,is your question solved?

Not yet. 
May be you can send an email to author?
